---

- name: Render bookstack container env file
  template:
    src: bookstack.env
    dest: "{{bookstack_web_env_file}}"
    owner: root
    group: root
    mode: 0600
  become: yes
  notify:
  - Restart Bookstack service

- name: Render bookstack unit file
  template:
    src: bookstack.service
    dest: /etc/systemd/system/bookstack.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Reload Systemd daemon
  - Restart Bookstack service

- name: Create Bookstack directories
  file:
    path: "{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  become: yes
  with_items:
  - "{{bookstack_web_config_dir}}"
  - "{{bookstack_web_log_dir}}"
  - "{{bookstack_web_www_dir}}"

- name: Start and Enable bookstack service
  systemd:
    name: bookstack
    state: started
    enabled: yes
  become: yes

- name: Render bookstack nginx config file
  template:
    src: bookstack.conf
    dest: "{{nginx_sites_available_dir}}/bookstack.conf"
    owner: http
    group: http
    mode: 0644
  become: yes
  notify:
  - Reload Nginx service

- name: Enable bookstack site
  file:
    src: "{{nginx_sites_available_dir}}/bookstack.conf"
    path: "{{nginx_sites_enabled_dir}}/bookstack.conf"
    state: link
    force: yes
    owner: http
    group: http
    mode: 0777
  become: yes
  notify:
  - Reload Nginx service
