---

- name: Pull Whoogle docker container
  docker_image:
    name: "{{whoogle_docker_image}}"
    source: pull
  become: yes
  notify:
  - Restart Whoogle service

- name: Render Whoogle unit file
  template:
    src: whoogle.service
    dest: /etc/systemd/system/whoogle.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Reload Systemd daemon
  - Restart Whoogle service

- name: Start and Enable Whoogle service
  systemd:
    name: whoogle.service
    state: started
    enabled: yes
  become: yes

- name: Render Whoogle nginx config file
  template:
    src: whoogle.conf
    dest: "{{nginx_sites_available_dir}}/whoogle.conf"
    owner: http
    group: http
    mode: 0644
  become: yes
  notify:
  - Reload Nginx service

- name: Enable Whoogle site
  file:
    src: "{{nginx_sites_available_dir}}/whoogle.conf"
    path: "{{nginx_sites_enabled_dir}}/whoogle.conf"
    state: link
    force: yes
    owner: http
    group: http
    mode: 0777
  become: yes
  notify:
  - Reload Nginx service
