---

- name: Update Pacman cache
  pacman:
    update_cache: yes
  become: yes

- name: Install Pacman packages
  pacman:
    name:
    - pacman-contrib
  become: yes

- name: Backup Pacman mirrorlist
  copy:
    remote_src: yes
    src: /etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist.backup
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Rank Pacman mirrors
  shell:
    cmd: >
      rankmirrors \
          -n 5 --max-time {{rankmirror_timeout}} \
          /etc/pacman.d/mirrorlist.backup > \
        /etc/pacman.d/mirrorlist.ranked
    creates: /etc/pacman.d/mirrorlist.ranked
  become: yes

- name: Overwrite Pacman mirrors
  copy:
    remote_src: yes
    force: yes
    src: /etc/pacman.d/mirrorlist.ranked
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644
  become: yes
