---

- name: Sync updated Pacman mirrorlist
  get_url:
    url: https://www.archlinux.org/mirrorlist/?country={{pacman_mirror_country}}&protocol=https&use_mirror_status=on
    dest: /etc/pacman.d/mirrorlist
    force: yes
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Enable servers in Pacman mirrorlist
  replace:
    path: /etc/pacman.d/mirrorlist
    regexp: "#Server"
    replace: "Server"
  become: yes

- name: Update Pacman cache
  pacman:
    update_cache: yes
  become: yes

- name: Upgrade system packages
  pacman:
    upgrade: yes
  become: yes
