---

- name: Create Spamass-Milter user
  user:
    name: sa-milt
    create_home: no
    shell: /usr/bin/nologin
    system: yes
  become: yes

- name: Install Spamass-Milter AUR package
  aur:
    name: spamass-milter
  become: yes
  become_user: aur_builder
  notify:
  - Restart Spamass-Milter service

- name: Render Spamass-Milter config file
  template:
    src: spamass-milter.conf
    dest: /etc/spamass-milter
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Restart Spamass-Milter service

- name: Render Spamass-Milter unit file
  template:
    src: spamass-milter.service
    dest: /etc/systemd/system/spamass-milter.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Reload Systemd daemon
  - Restart Spamass-Milter service

- name: Start Spamass-Milter service
  systemd:
    name: spamass-milter
    state: started
    enabled: yes
  become: yes
