---

- name: Create Spamass-Milter user
  user:
    name: sa-milt
    create_home: no
    shell: /usr/bin/nologin
    system: yes
  become: yes

- name: Install Spamass-Milter build packages
  pacman:
    name:
    - gcc-libs
    - spamassassin
    - libmilter # (make)
    - postfix # (optional)
  become: yes

- name: Clone Spamass-Milter AUR package
  git:
    repo: https://aur.archlinux.org/spamass-milter.git
    dest: /opt/aur/spamass-milter/
    depth: 1
  become: yes
  become_user: nobody

- name: Build Spamass-Milter AUR package
  command:
    chdir: /opt/aur/spamass-milter/
    cmd: makepkg
    creates: /opt/aur/spamass-milter/spamass-milter-0.4.0*.pkg.tar.xz
  environment:
    SPAMC: /usr/bin/vendor_perl/spamc
  become: yes
  become_user: nobody

- name: Install Spamass-Milter AUR package
  command:
    cmd: >
      pacman --upgrade --noconfirm
        /opt/aur/spamass-milter/spamass-milter-0.4.0-1-x86_64.pkg.tar.xz
    creates: /usr/bin/spamass-milter
  become: yes
  notify:
  - Restart Spamass-Milter service

- name: Render Spamass-Milter config file
  template:
    src: spamass-milter.conf
    dest: /etc/spamass-milter
    owner: root
    group: root
    mode: 644
  become: yes
  notify:
  - Restart Spamass-Milter service

- name: Render Spamass-Milter unit file
  template:
    src: spamass-milter.service
    dest: /etc/systemd/system/spamass-milter.service
    owner: root
    group: root
    mode: 644
  become: yes
  notify:
  - Reload Systemd daemon
  - Restart Spamass-Milter service

- name: Start Spamass-Milter service
  systemd:
    name: spamass-milter
    state: started
    enabled: yes
  become: yes
