---

- name: Install Fail2Ban package
  pacman:
    name: fail2ban
  become: yes

- name: Render Fail2Ban config file
  template:
    src: jail.local
    dest: "{{fail2ban_jail_file}}"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Restart Fail2Ban service

- name: Start and Enable Fail2Ban service
  systemd:
    name: fail2ban.service
    state: started
    enabled: yes
  become: yes
