---

- name: Install Nginx package
  pacman:
    name: nginx
  become: yes

- name: Make Nginx config directories
  file:
    path: "{{item}}"
    state: directory
  become: yes
  with_items:
  - "{{nginx_ssl_dir}}"
  - "{{nginx_sites_available_dir}}"
  - "{{nginx_sites_enabled_dir}}"

- name: Link Nginx SSL files
  file:
    src: "{{item.src}}"
    path: "{{item.dest}}"
    owner: http
    group: http
    mode: 0777
    state: link
    force: yes
  become: yes
  with_items:
  - src: "{{dh_param_file}}"
    dest: "{{nginx_ssl_dhparam}}"
  - src: "{{certbot_ssl_dir}}/fullchain.pem"
    dest: "{{nginx_ssl_certificate}}"
  - src: "{{certbot_ssl_dir}}/privkey.pem"
    dest: "{{nginx_ssl_certificate_key}}"
  - src: "{{certbot_ssl_dir}}/fullchain.pem"
    dest: "{{nginx_ssl_trusted_certificate}}"

- name: Render Nginx config file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Reload Nginx service

- name: Start and Enable Nginx service
  systemd:
    name: nginx.service
    state: started
    enabled: yes
  become: yes

- name: Install Nginx Certbot post-deploy hook
  copy:
    src: nginx-post-deploy.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/nginx.sh
    owner: root
    group: root
    mode: 0744
  become: yes

- name: Install Fail2Ban jail config
  copy:
    src: fail2ban.local
    dest: "{{fail2ban_jail_dir}}/nginx.local"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Restart Fail2Ban service
