---

- name: Install Docker packages
  pacman:
    name:
    - docker
    - python-pip
  become: yes

- name: Install Docker Python packages
  pip:
    name:
    - docker
  become: yes

- name: Start and Enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
