---

- hosts: dataserver
  roles:
  - admin
  - hostname
  - locale
  - fail2ban
  - mail-nfs-export
  - mysql
  - postgres
  - redis
  - bookstack-db

- hosts: webserver
  roles:
  - admin
  - hostname
  - locale
  - fail2ban
  - certbot
  - nginx
  - bookstack-web
  - whoogle
  - resume

- hosts: filterserver
  roles:
  - admin
  - hostname
  - locale
  - fail2ban
  - clamav
  - spamassassin

- hosts: mailserver
  roles:
  - admin
  - hostname
  - locale
  - fail2ban
  - clamav-milter
  - spamass-milter
  - opendkim
  - dovecot
  - postfix
