---

- hosts: database
  roles:
  - hostname
  - fail2ban
  - mysql
  - bookstack-db

- hosts: webserver
  roles:
  - hostname
  - fail2ban
  - certbot
  - nginx
  - bookstack-web
  - resume

- hosts: filterserver
  roles:
  - hostname
  - fail2ban

- hosts: mailserver
  roles:
  - hostname
  - fail2ban
  - clamav-milter
  - spamass-milter
  - opendkim
  - dovecot
  - postfix
