---

- name: Pull PostfixAdmin docker container
  docker_image:
    name: "{{postfixadmin_web_docker_image}}"
    source: pull
    force_source: yes
  become: yes
  notify:
  - Restart PostfixAdmin service

- name: Render PostfixAdmin container env file
  template:
    src: postfixadmin.env
    dest: "{{postfixadmin_web_env_file}}"
    owner: root
    group: root
    mode: 0600
  become: yes
  notify:
  - Restart PostfixAdmin service

- name: Render PostfixAdmin unit file
  template:
    src: postfixadmin.service
    dest: /etc/systemd/system/postfixadmin.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
  - Reload Systemd daemon
  - Restart PostfixAdmin service

- name: Start and Enable PostfixAdmin service
  systemd:
    name: postfixadmin.service
    state: started
    enabled: yes
  become: yes

- name: Render PostfixAdmin nginx config file
  template:
    src: postfixadmin.conf
    dest: "{{nginx_sites_available_dir}}/postfixadmin.conf"
    owner: http
    group: http
    mode: 0644
  become: yes
  notify:
  - Reload Nginx service

- name: Enable PostfixAdmin site
  file:
    src: "{{nginx_sites_available_dir}}/postfixadmin.conf"
    path: "{{nginx_sites_enabled_dir}}/postfixadmin.conf"
    state: link
    force: yes
    owner: http
    group: http
    mode: 0777
  become: yes
  notify:
  - Reload Nginx service
